/* eslint-disable import/no-anonymous-default-export */

export default {
        0: {name: "Damaso", children: [9, 5], alive: true, murderer: false},
        1: {name: "Clara", children: [9], alive: true, murderer: false},
        2: {name: "Cabele", children: [10, 11], alive: true, murderer: false},
        3: {name: "Adriele", children: [10, 11], alive: true, murderer: false},
        4: {name: "Bruno", children: [12, 13], alive: true, murderer: false},
        5: {name: "Indiara", children: [12, 13], alive: true, murderer: true},
        6: {name: "Brian", children: [], alive: true, murderer: false},
        7: {name: "Emily", children: [4,6], alive: true, murderer: false},
        8: {name: "Daniela", children: [4,6], alive: true, murderer: false},
        9: {name: "Paulo Henrique", children: [5], alive: true, murderer: false},
        10: {name: "Joana", children: [5], alive: true, murderer: false},
        11: {name: "Bruno", children: [], alive: true, murderer: false},
        12: {name: "Damaso", children: [], alive: true, murderer: true},
        13: {name: "Blanco", children: [], alive: true, murderer: false},
        14: {name: "Joao", children: [4,6], alive: true, murderer: false},
        15: {name: "Maria", children: [4,6], alive: true, murderer: false},
        16: {name: "Jose", children: [5], alive: true, murderer: false},
        17: {name: "Joana", children: [5], alive: true, murderer: false},
        18: {name: "Bruno", children: [], alive: true, murderer: false},
        19: {name: "Damaso", children: [], alive: true, murderer: true},
        20: {name: "Blanco", children: [], alive: true, murderer: false},
        21: {name: "Joao", children: [4,6], alive: true, murderer: false},
        22: {name: "Maria", children: [4,6], alive: true, murderer: false},
        23: {name: "Jose", children: [5], alive: true, murderer: false},
        24: {name: "Joana", children: [5], alive: true, murderer: false},
        25: {name: "Bruno", children: [], alive: true, murderer: false},
        26: {name: "Damaso", children: [], alive: true, murderer: true},
        27: {name: "Blanco", children: [], alive: true, murderer: false},
        28: {name: "Joao", children: [4,6], alive: true, murderer: false},
        29: {name: "Maria", children: [4,6], alive: true, murderer: false},
        30: {name: "Jose", children: [5], alive: true, murderer: false},
        31: {name: "Joana", children: [5], alive: true, murderer: false},
        32: {name: "Bruno", children: [], alive: true, murderer: false},
        33: {name: "Damaso", children: [], alive: true, murderer: true},
        34: {name: "Blanco", children: [], alive: true, murderer: false},
        35: {name: "Joao", children: [4,6], alive: true, murderer: false},
        36: {name: "Maria", children: [4,6], alive: true, murderer: false},
        37: {name: "Jose", children: [5], alive: true, murderer: false},
}